### PR TITLE
Mnml rebase - function oriented prompt

### PR DESCRIPTION
**Pull request by jedahan**
Inspired by #226 and https://github.com/subnixr/minimal

This is a first draft rewrite on top of mnml, and I'd love some testing, writing functions, general feedback and feel.

### the good
- less lines of code, less characters of code
- simpler to customize left and right prompt
- no global concept of pinning (individual plugins can define an env variable that makes sense)
- way less abstractions (no plugins, no setup/check/render)
- easier to turn non-geometry specific code into generally useful zsh modules
- rprompt is still async <3
- ported every plugin we ship
- ~~it feels faster? total placebo probably~~

### the bad
- will break everyones plugins, prompts (but really easy to port)
- will break everyones env variable customizations
 - I renamed env variables for consistency, but maybe we can have a `lib/deprecated` where we check for a mapping of environment variables and print warnings to help with the transition?
- ~~I think I missed the title changing stuff in hooks~~ added back title changes

### the ugly
- ~~re-introduced weird tab width bug (should be easy to re-fix)~~ fixed with no hack!
- `geometry_` prefix everywhere, maybe we can come up with a better one
- very little testing - I've been running with all plugins on but still, need more testing
- probably made some opinionated changes that could cause friction
- ~~not sure about the mnml widgets code and if we should bind it~~ only bound what we needed
- should we add the "enter on blank line does a thing" feature?

### CODE REVIEW

**Comment by jedahan** [comment]
before
```shell
--------------------------------------------------------------------------------
 Language             Files        Lines        Blank      Comment         Code
--------------------------------------------------------------------------------
 Z Shell                 20         1375          253          244          878
 Markdown                17          913          308            0          605
 Bourne Shell             1          117           20            9           88
--------------------------------------------------------------------------------
 Total                   38         2405          581          253         1571
--------------------------------------------------------------------------------
```
after
```shell
--------------------------------------------------------------------------------
 Language             Files        Lines        Blank      Comment         Code
--------------------------------------------------------------------------------
 Z Shell                 19         1221          218          241          762
 Markdown                 6          626          211            0          415
 Bourne Shell             1          117           20            9           88
--------------------------------------------------------------------------------
 Total                   26         1964          449          250         1265
--------------------------------------------------------------------------------
```

**Comment by jedahan** [comment]
#3 is active in this fork
Now that its easier to modify the left and right prompt, it would be nice to port #216 to be generic in geometry.zsh, looking at `$PROMPT` as a whole, not just the path plugin which was kinda hard-coded before.

**Comment by jedahan** [comment]
#3 no longer applies, yay!

**Comment by jedahan** [comment]
Okay @desyncr @justmendes I feel like this PR is in good shape for testing :)

**Comment by jedahan** [comment]
Went from 676 lines of zsh to 477
Went from 512 lines of markdown to 283

```
▲ loc --exclude lib/zsh-async                                   geometry master 9d ⬢  ⚙
--------------------------------------------------------------------------------
 Language             Files        Lines        Blank      Comment         Code
--------------------------------------------------------------------------------
 Z Shell                 19          967          188          103          676
 Markdown                16          766          254            0          512
--------------------------------------------------------------------------------
 Total                   35         1733          442          103         1188
--------------------------------------------------------------------------------
▲ gco mnml                                                      geometry master 9d ⬢  ⚙
Switched to branch 'mnml'
Your branch is up to date with 'origin/mnml'.
▲ loc --exclude lib/zsh-async                                     geometry mnml 3m ⬢  ⚙
--------------------------------------------------------------------------------
 Language             Files        Lines        Blank      Comment         Code
--------------------------------------------------------------------------------
 Z Shell                 18          686          137           72          477
 Markdown                 4          431          148            0          283
--------------------------------------------------------------------------------
 Total                   22         1117          285           72          760
--------------------------------------------------------------------------------
▲                                                                 geometry mnml 3m ⬢  ⚙
```

**Comment by jedahan** [comment]
* all environment variables are editable on the fly
* all functions are editable on the fly
  * you can even have undefined functions in PROMPT/RPROMPT arrays and define them later
* 33% less code

```zsh
 ▲ loc --exclude lib/zsh-async                         code/geometry/geometry mnml 2m ⬢
--------------------------------------------------------------------------------
 Language             Files        Lines        Blank      Comment         Code
--------------------------------------------------------------------------------
 Z Shell                 18          627          136           66          425
 Markdown                 4          430          149            0          281
--------------------------------------------------------------------------------
 Total                   22         1057          285           66          706
--------------------------------------------------------------------------------
```

**Comment by jedahan** [comment]
Less than half the lines of code!

```zsh
▲ loc --exclude lib/zsh-async                       code/geometry/geometry mnml 24s ⬢  ⚙
--------------------------------------------------------------------------------
 Language             Files        Lines        Blank      Comment         Code
--------------------------------------------------------------------------------
 Z Shell                 16          508          127           50          331
 Markdown                 4          430          149            0          281
--------------------------------------------------------------------------------
 Total                   20          938          276           50          612
```

**Comment by frm** [comment]
👏 let me know when you think this is stable enough for a lengthy review.

**Comment by jedahan** [comment]
I think this is in a stable enough state - most of my recent changes are cosmetic / can be made in future PRs.

I have only tested on alacritty, running tmux, on macOS 10.13. The least tested functions are `hg`, `kube`, `virtualenv` and `ruby`

**Comment by jedahan** [comment]
I rebased all the commits to make this easier to review in #233

**Pull request closed without merging**
