### PR TITLE
kube_namespace always resolves to default

### PR DESCRIPTION
**Pull request by olegTarassov**
Switch order because appending color to kube_context fails filter for kube_namespace

### CODE REVIEW

**Comment by olegTarassov** [comment]
any update on this :)

**Comment by kyounger** [comment]
This might be fixed with #271? It was just merged, so might be worth checking. With that PR, I get proper namespace showing. I did the refactor for that PR, so would be willing to investigate if your issue still persists.

**Comment by olegTarassov** [comment]
Very nice refactoring!
Love the:

```bash
kubectl config view --minify --output "jsonpath={..namespace}
```

Yes it solves the issue but it removed the option to omit the k8s version print.

**Comment by kyounger** [comment]
@olegTarassov like the git prompt function, you can now just piece together your own segments , and leave out the geometry_kube_version segment altogether. So it still allows you to omit it.

e.g. `GEOMETRY_RPROMPT=(geometry_git geometry_exec_time geometry_kube_symbol geometry_kube_context geometry_kube_namespace)`

**Comment by olegTarassov** [comment]
that is definitely the better approach

**Comment by olegTarassov** [comment]
just tested, it works but now you lose the separator because its not initialized:

```
  local separator=${GEOMETRY_KUBE_SEPARATOR:-"|"}
  echo -n ${(pj.$separator.)geometry_kube_details}
```

**Comment by kyounger** [comment]
What's the value of your GEOMETRY_RPROMPT?

**Comment by olegTarassov** [comment]
```
GEOMETRY_INFO=
GEOMETRY_GIT_GREP=ag
GEOMETRY_KUBE_CONTEXT_COLOR=red
GEOMETRY_KUBE_NAMESPACE_COLOR=cyan
GEOMETRY_KUBE_SEPARATOR="|"

GEOMETRY_RPROMPT+=(
    geometry_virtualenv
    geometry_git
    geometry_kube_symbol
    geometry_kube_context
    geometry_kube_namespace
)
```

**Comment by kyounger** [comment]
Right the separator is only used with the `geometry_kube` function. If you piece your prompt together with the helper functions, you'll have to insert the separators yourself.

**Pull request closed without merging**
