### PR TITLE
Add plugin support for left prompt (PROMPT)

### PR DESCRIPTION
**Pull request by desyncr**
- PROMPT now supports plugin registration with the same mechanism as RPROMPT.
- Added `path` and `hostname` plugins for PROMPT

### PENDING
  - [x] Update README
  - [x] Add configuration examples

From: https://trello.com/c/U2xwxwzJ/13-enable-left-prompt-customization

# Configuration examples

## Default

plugable-prompt

```
GEOMETRY_PROMPT_PLUGINS_PRIMARY=(path hostname)
GEOMETRY_PROMPT_PLUGINS_SECONDARY=(exec_time jobs git hg)
```

## Full

screenshot from 2017-11-25 14-41-13

```
GEOMETRY_PROMPT_PLUGINS_PRIMARY=(path hostname)
GEOMETRY_PROMPT_PLUGINS_SECONDARY=(exec_time jobs node ruby rustup virtualenv docker_machine git hg)
```

## Custom prompt

screenshot from 2017-11-25 18-59-28

```
GEOMETRY_PROMPT_SUFFIX=$'\n └─▪'
GEOMETRY_PROMPT='┌─ [$(whoami)]'
GEOMETRY_PROMPT_PLUGINS_PRIMARY=(path hostname)
```

## Movable plugins

plugable-prompt-node

```
GEOMETRY_PROMPT_PLUGINS_PRIMARY=(path node)
GEOMETRY_PROMPT_PLUGINS_SECONDARY=(git)

```

### CODE REVIEW

**Comment by desyncr** [comment]
This is done. Let me know what you guys think!

**Review by frm — APPROVED** [review]
Looking good. This separation feels much cleaner.

**Comment by desyncr** [comment]
@fribmendes @jedahan Do we merge it?

**Comment by frm** [comment]
@desyncr it's a go from my end.

**Review by jedahan — APPROVED** [review]
I like the migration from lib to plugins for exec_time.

Hostname plugin is great

path readme is good

okay with path plugin containing hash color for now, might wanna extract to lib in the future

**Pull request merged**
