### PR TITLE
Fix fatal error ambiguous argument @

### PR DESCRIPTION
**Pull request by dio-az**

### CODE REVIEW

**Comment by frm** [comment]
What issue is this? How long has it been around and what terminal and zsh versions does it affect?

**Comment by dio-az** [comment]
@frmendes I'm using prezto with zsh v5.1.1.

**Comment by desyncr** [comment]
I'm gonna test this out later today with zsh 5.1.1 and above. Should be good to go.

**Comment by frm** [comment]
@diogoazevedos the fix should be good to go, thanks. But can you create a corresponding issue to document it in case anyone comes looking for a similar error?

**Comment by desyncr** [comment]
It seems I can't reproduce it. Tried with `5.1.1` and `5.2`.

**Comment by dio-az** [comment]
@frmendes @desyncr I'll provide more details about error when I reach the computer. I'm using in my terminal zgen with prezto, take a look in my [.zshrc](https://github.com/diogoazevedos/terminal/blob/master/.zshrc).

**Comment by dio-az** [comment]
I execute the follow command in my terminal:

``` shell
$ git merge-base @ @{u} 2>&1
fatal: Not a valid object name @u

$ git rev-parse @{u} 2>&1
@u
fatal: ambiguous argument '@u': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

And this causes an error with the ⇡ and ⇣.
Always showing them.

**Comment by desyncr** [comment]
Further looking into it, it looks like it's a prezto-only issue. Not sure what it's trying to do, thou.

Edit: It's the `BRACE_CCL` option set up in [`environment` module](https://github.com/sorin-ionescu/prezto/blob/master/modules/environment/init.zsh#L19).

**Comment by desyncr** [comment]
Merged. Thanks @diogoazevedos

**Pull request merged**
