### PR TITLE
Add trello badge 

### PR DESCRIPTION
**Pull request by ajayns**
I'd like to make my first PR on GitHub by resolving issue #163 

The badge looks like this:
[Trello](https://trello.com/b/GfM4e6Ro/geometry)

### CODE REVIEW

**Comment by desyncr** [comment]
Looking great!

**Review by desyncr — APPROVED** [review]
Looking good!

**Comment by desyncr** [comment]
@ajayns Mergin as is. Thanks a lot!

**Comment by ajayns** [comment]
Happy to help :)

**Pull request merged**
