### PR TITLE
Update screenshots

### PR DESCRIPTION
**Pull request by frm**
This took me a little longer than what I wanted. But here are the screenshots.

@desyncr I'd love some feedback particularly regarding [this one](https://github.com/frmendes/geometry/blob/master/screenshots/long_running.png) which I havent updated yet. I'm not really sure what to do without having it end up too empty.

### CODE REVIEW

**Comment by desyncr** [comment]
Issuing a couple of long-running commands would be enough I think.

They look great :tada: . Look out for the file size thou.

**Comment by frm** [comment]
File size has to do with retina screens. The previous ones look awful on recent macs.

**Comment by frm** [comment]
@desyncr feedback on that last one?

**Comment by desyncr** [comment]
Looking good :+1:

**Pull request merged**
