### PR TITLE
They looked like multiple steps.

### PR DESCRIPTION
**Pull request by Indyandie**
Just to make it a little clearer.

### CODE REVIEW

**Comment by desyncr** [comment]
What about:

    Option 1: Using antigen
    Option 2: Using oh-my-zsh
    Option 3: Using zplug

Could we give it a try?

**Comment by Indyandie** [comment]
how about 

`### Install using <method>`

**Comment by desyncr** [comment]
Yeah, much better.

**Comment by desyncr** [comment]
@Indyandie Are you up to implement the format you described [above](https://github.com/frmendes/geometry/pull/103#issuecomment-277501033)? Let me know :)

**Comment by Indyandie** [comment]
@desyncr okay we should be all good now 👍🏾👍🏾

**Review by desyncr — APPROVED** [review]
Looking good!

**Pull request merged**
