### PR TITLE
Fix git branch expansion

### LINKED ISSUE #137: Git plugin doesn't escape branch names
https://github.com/njhartwell/pw3nage means we are vulnerable

### PR DESCRIPTION
**Pull request by desyncr**
Handled a basic test case:

    $ git init
    $ git branch '$(ls)'

Shown as:

    $(ls) :: no commits :: ⬢ :: ar :: 0 files, 0
    

Fixes #137

### CODE REVIEW

**Comment by jedahan** [comment]
Localoptions looks awesome, will test tonight

**Comment by jedahan** [comment]
Confirmed that it works with https://github.com/njhartwell/pw3nage :)

**Review by jedahan — APPROVED** [review]
This is the best fix I've seen, yay!

**Review by frm — APPROVED** [review]
❤️

**Comment by frm** [comment]
Hey @desyncr, you should suggest this fix in [njhartwell/pw3nage]. See https://github.com/njhartwell/pw3nage/pull/2

[njhartwell/pw3nage]: https://github.com/njhartwell/pw3nage

**Comment by desyncr** [comment]
Thanks! Will do!

**Pull request merged**
