### PR TITLE
Updated README and fixed a few minor errors

### PR DESCRIPTION
**Pull request by cnguy**
Hello, not sure if this needs a PR, but I just wanted to fix a few inconsistencies and some typos in the README.

### CODE REVIEW

**Review by desyncr — APPROVED** [review]
Docs improvements are always welcome! Thanks!

**Comment by desyncr** [comment]
Anything else to add or can I just merge? @ChauTNguyen

**Comment by cnguy** [comment]
@desyncr I think that's pretty much it. Let me know if you have any issues!

**Review by desyncr — APPROVED** [review]
Looking good!

**Pull request merged**
