### PR TITLE
Mnml rebase

### PR DESCRIPTION
**Pull request by jedahan**
This is a second draft rewrite on top of mnml, superseding #229. I rebased the commits and explained things more to make it slightly easier to review. If you already started a review on that branch, feel free to close this one. I will stop making commits and changes for one week because its unfair to y'all.

* plugins are now functions
* left and right prompt are dynamic - add and remove functions in any order and it just works
* pinning is up to the functions with environment variables
* lots of environment variables have been renamed, which will break configs
* I've tested on alacritty on macOS 10.13 

```zsh
▲ loc --exclude lib/zsh-async                                   geometry master 9d ⬢  ⚙
--------------------------------------------------------------------------------
 Language             Files        Lines        Blank      Comment         Code
--------------------------------------------------------------------------------
 Z Shell                 19          967          188          103          676
 Markdown                16          766          254            0          512
--------------------------------------------------------------------------------
 Total                   35         1733          442          103         1188
▲ gco mnml-rebase                                               geometry master 9d ⬢  ⚙
Switched to branch 'mnml-rebase'
▲ loc --exclude lib/zsh-async                code/geometry/geometry ⇡ mnml-rebase 15m ⬢
--------------------------------------------------------------------------------
 Language             Files        Lines        Blank      Comment         Code
--------------------------------------------------------------------------------
 Z Shell                 16          492          124           47          321
 Markdown                 4          430          149            0          281
--------------------------------------------------------------------------------
 Total                   20          922          273           47          602
```

### CODE REVIEW

**Comment by frm** [comment]
@jedahan is this stable? I was thinking of using this for a while to test it out and see if any issues pop up

**Comment by jedahan** [comment]
It is stable, there is one known issue - geometry_exec_time does not work yet. Otherwise I have been on this branch day-to-day and it feels good. Please try it out!

**Comment by jedahan** [comment]
I fixed exec_time in another branch, but for the sake of making this easier to review I am leaving this branch as-is.

**Comment by jedahan** [comment]
Closing for #238

**Pull request closed without merging**
