### PR TITLE
Extract time helper functions to a separate file

### PR DESCRIPTION
**Pull request by frm**
If you load the `git` plugin without `exec_time`, the following error happens:

```shell
prompt_geometry_git_time_since_commit:9: command not found: prompt_geometry_seconds_to_human_time
master :: •
```

Sample configuration:

```shell
GEOMETRY_PROMPT_PLUGINS_PRIMARY=(git)
GEOMETRY_PROMPT_PLUGINS_SECONDARY=(path)
```

This happens because `git` depends on functions defined in `exec_time`. This PR solves this by extracting these functions to a separate `lib/time.zsh` file.

### CODE REVIEW

**Comment by frm** [comment]
Ping @desyncr @jedahan

**Comment by jedahan** [comment]
will look at this evening (in ~4 hours)

**Comment by jedahan** [comment]
thanks for being so patient

**Comment by frm** [comment]
All good :)

**Pull request merged**
