### PR TITLE
WIP: Add screencast gif

### PR DESCRIPTION
**Pull request by desyncr**
- Add sub-theming section
- Publish on reddits/twitter etc

### CODE REVIEW

**Review by jedahan — APPROVED** [review]

**Review by frm — APPROVED** [review]

**Comment by frm** [comment]
What's keeping this as WIP?

**Comment by desyncr** [comment]
I need to add a subtheming section. I'll add sub-themes examples on the wiki for now (rather than it's own repos, for simplicity).

**Comment by desyncr** [comment]
I could merge as-is. And create a new PR. @fribmendes is that OK?

**Comment by frm** [comment]
Go for it 👍

**Pull request merged**
