### PR TITLE
git_status: simplify tracked file dirty check

### PR DESCRIPTION
**Pull request by jedahan**
i was getting some weird quoting behaviour before in my shell, this seems reasonable

### CODE REVIEW

**Comment by jedahan** [comment]
i am not sure if i should use HEAD or something else, as maybe if you are in detached head this breaks?

**Comment by frm** [comment]
re the HEAD subject, I was having issues in detached HEAD a few versions back so that reasoning makes sense. Can you try and see what happens with no argument?

**Comment by jedahan** [comment]
I tested in a detached head and it still seems to work. git diff requires a commit-ish thing, so HEAD seems fine.

no argument doesn't work.

**Review by frm — APPROVED** [review]
Cool, let's go for it

**Pull request merged**
