### PR TITLE
Redirected error messages to stderr

### PR DESCRIPTION
**Pull request by keelan542**

### CODE REVIEW

**Review by desyncr — COMMENTED** [review]
Seems to work. It stoke me a wrong at first. But it's perfectly valid.

**Comment by desyncr** [comment]
Fixes #143

**Review by frm — APPROVED** [review]

**Comment by desyncr** [comment]
Okay let's go. @keelan542 Thanks for the contribution!

**Comment by keelan542** [comment]
No problem !  @desyncr

**Pull request merged**
